### ISSUE TITLE
Understanding output

### ISSUE THREAD

**Issue by Ram-Nagar** [stevemussmann/admixturePipeline#13]
Hi Steve, 
I could successfully run your admixturePipeline, however I am not able to make out the appropriate cluster in population. . Could you please have a look at plots, suggest me how I decide the appropriate clusters in the population? 

Thanks 
Ram 
![cv_file MajClust](https://user-images.githubusercontent.com/18412525/207803050-7c2dd08d-6474-447a-9b0b-bb60607c2183.png)
![loglikelihood_file MajClust](https://user-images.githubusercontent.com/18412525/207803090-ec6b22e6-1637-4323-9843-12637f371628.png)

**Comment by stevemussmann** [comment]
Hi Ram,

Sorry for the delayed response. Generally I look for the K value associated with the lowest CV value. However, you have a lot of CV values that are very similar to one another for a range of Ks. Without knowing anything else about your data, it's possible there is not a single best K that describes genetic clusters in your system. I've seen similar patterns in my work when I've had hierarchical population structure in my data (e.g., fish exist in two or more isolated river basins with additional population divisions occurring within those basins). 

-Steve
