### ISSUE TITLE
Support vcf input

### ISSUE THREAD

**Issue by Banthandor** [stevemussmann/admixturePipeline#14]
Hi,

Thank you for publishing this software. 

Unfortunately, vcf input is currently not possible due to the fact that the vcf-query requires a gzipped vcf file whereas vcftools requires a non compressed vcf file. 

Luckily this can be easily fixed :)

Cheers,
Sam

**Comment by stevemussmann** [comment]
Hi Sam,

Could you please send me any error message you are receiving? I am unable to replicate this problem, and the documentation for vcf-query shows it working on both non-compressed and gzipped vcf files:

https://vcftools.sourceforge.net/perl_module.html#vcf-query

-Steve

**Comment by stevemussmann** [comment]
I tested this on the uncompressed example.vcf file included in this repository and vcf-query returned valid output:

```admixturePipeline/example_files$ vcf-query -l example.vcf | head -10
The column name contains leading/trailing spaces, removing: 'INFO    '
1groupA001
1groupA002
1groupA003
1groupA004
1groupB001
1groupB002
1groupB003
1groupC001
1groupD001
1groupD003```

**Comment by Banthandor** [comment]
Hi Steven,

I should have tested the example vcf, which indeed returned expected output. My apologies.
Using another vcf of my own, I was able to verify that it there was a problem with the vcf header. I suspect this has something to do with an earlier filtering with vcftools, which gave me problems before.

Many thanks for your input.

Kind regards,
Sam

**Comment by stevemussmann** [comment]
Sounds good, I'm going to mark this as resolved,

-Steve
