### ISSUE TITLE
Lack of the test files

### ISSUE THREAD

**Issue by NikolaBio** [stevemussmann/admixturePipeline#4]
Can you please provide **popmap.txt** and **.vcf** example test files. That way it will be much easier to test the setup of whole pipeline. Just popmap.txt can be sufficient for the beginning.

**Comment by stevemussmann** [comment]
Hi,

I'm away from my files for almost the next month. You can find an example
popmap file in my comp-d directory
https://github.com/stevemussmann/Comp-D_MPI/tree/master/example

The vcf file is a standard vcf format file processed by vcftools, so
anything vcftools can handle should be fine.

I hope that helps,

-steve

**Comment by stevemussmann** [comment]
Example files have been added.
