### ISSUE TITLE
Remove individuals in VCF but not in popmap

### ISSUE THREAD

**Issue by tkchafin** [stevemussmann/admixturePipeline#9]
Currently it will run, but then the files won't match the labels provided in _pops.txt and _inds.txt. 

Could alternatively add an option, but since the pop-up is required I think having the default behavior be to remove individual not in the popmap makes sense. Could always add an option to by-pass that, if anyone wants it

(By the way, I can work on this later but don't have time today. Partially just putting this here as a reminder.)

**Comment by stevemussmann** [comment]
I think this might be a python version thing. It's been consistent on my computer, but Bradley contacted me about this once as well. I wasn't able to replicate it at the time.

**Comment by tkchafin** [comment]
In my case I'm using the blacklist but not filtering on missing data, and individuals in VCF but not popmap ending up getting through.

**Comment by stevemussmann** [comment]
Do you have files you can send me?

**Comment by stevemussmann** [comment]
I didn't understand what you were asking the first time I read this and thought you were reporting a bug.

Anyways, I implemented this feature as default behavior today. In summary, I use vcf-query to get a list of all individuals from the vcf file, then subtract the popmap list from the vcf file list to make a new "discard" list. The individuals from the discard list are removed when vcftools is called to convert the vcf file to plink format. These changes have been pushed to the repository. The pipeline didn't previously rely upon vcf-query, which is a perl script included with vcftools, so make sure you either link to it in your path, or ensure that you have installed the entire vcftools package ("sudo make install" will do this when you compile the vcftools package), or explicitly link vcf-query in your path.
